server {

    listen 80;

    location / {

        proxy_pass http://atlas-frontend:5173;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;

        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;

    }

    location /usuarios {

        proxy_pass http://api-service:3000/usuarios;

    }

    location /clima {

        proxy_pass http://api-service:3000/clima;

    }

}